#pragma once
#include "utils/hwid.h"
#include <iostream>
#include <stdio.h>
#include "auth/auth.h"
#include "utils/xor.h"
#include "utils/utils.h"
#include "utils/base64.h"
#include <wincrypt.h>
#include <time.h>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <comutil.h>
#include <cstdlib>